### ISSUE TITLE
cloudfront domain verification

### ISSUE THREAD

**Issue by superuser5** [rvrsh3ll/FindFrontableDomains#11]
Thank you for the great work, I tested some cloudfrontable domains and they report with the following error:
 
> curl  -H "Host: <my_cldoudfront_domain>.cloudfront.net" "https://smile.amazon.com/"
<html>
<head><title>421 Misdirected Request</title></head>
<body bgcolor="white">
<center><h1>421 Misdirected Request</h1></center>
<hr><center>CloudFront</center>
</body>
</html>

**Comment by rvrsh3ll** [comment]
cloudfont has mitigated domain fronting. I'll remove it from the script soon. thanks
